### ISSUE TITLE
logging happens twice 

### ISSUE THREAD

**Issue by CDitzel** [tensorpack/dataflow#1]
Loving dataflow so far, good job guys. 

However, why is it, that the logging of information to standard out always occurs twice?

With a fresh install, the following example 

import dataflow as D
from tensorpack.utils import logger

```
class test(D.DataFlow):
    num = 100000

    def __len__(self):
        return self.__class__.num

    def __iter__(self):
        logger.info("how often")
        for i in range(self.__class__.num):
            yield i


df = test()


for _ in df:
    pass
```
outputs 

[1126 18:03:49 @dataflowtest.py:12] how often
[1126 18:03:49 @dataflowtest.py:12] how often

**Comment by ppwwyyxx** [comment]
You need either 
```
import tensorpack.dataflow as D
from tensorpack.utils import logger
```

or 
```
import dataflow as D
from dataflow.utils import logger
```

**Comment by ppwwyyxx** [comment]
It is because the code between tensorpack and dataflow is shared and they used the same logger name. This is now fixed in latest version.
